<form action="/edit/add" method="post">
    title:
    <input type="text" name='title' value='<?php echo $data->title; ?>' class="form-control">
    <br><br>
    data:
    <textarea name="desc" id="" cols="30" rows="10" class="form-control"><?php echo $data->desc; ?></textarea>
    <br><br>
    <input type="hidden" name="id" value='<?php echo $data->id?>'>
    <input type="submit" value="submit">
</form>
