<?php
include_once APP_PATH."/assets/header.php";
session_start();
?>
<br>
<img src="../../../public/assets/img/headerimg.jpg.jpg" alt=""  width=100% height=400>
<?php
foreach ($data as $key => $value) {
echo "<div class='container m-2 p-2 border'>
<h2 class='text-center m-1 text-primary'>$value->title</h2>
<div class='overflow-hidden p-2 ' style='height:200px;'>$value->desc</div>
";
if($value->user_id==$_SESSION['isLogin']){
  echo "<a class='btn btn-info' href='edit?id=$value->id'>Edit</a>";
}
 echo "</div>";
}
