<a href='admin/add' class="btn btn-primary p-1 m-2 ">Add Resturant </a>
<a href='admin/manager' class="btn btn-primary p-1 m-2">Add Manager </a>
<table class="table table-hovered table-striped table-bordered">
    <caption>table shows orders detail</caption>
    <thead>
        <th>Customer Name</th>
        <th>Customer Address</th>
        <th>Resturant Name </th>
        <th>Cuisine</th>
        <th>time</th>
    </thead>
    <tbody>
        <?php
        echo $data;
        ?>
    </tbody>
</table>
<table class="table table-hovered table-striped table-bordered">
    <caption>table shows users detail</caption>
    <thead>
        <th>Customer Name</th>
        <th>Customer email</th>
        <th>Customer PinCode </th>
        <th>Role</th>
    </thead>
    <tbody>
        <?php
        foreach ($user as $key => $value) {
           echo "<tr><td>$value->name</td><td>$value->email</td><td>$value->pincode</td><td>$value->role</td></tr>";
        }
        ?>
    </tbody>
</table>